server:
  port: 8080


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #        user
        - id: user-service
          #          cái này dùng với eureka
          uri: lb://user-service
          #          uri: http://localhost:8000 cái này dùng tĩnh
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        #          order
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
        #          product
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
        #          category
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/category-service/**
          filters:
            - StripPrefix=1
        #          file
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file-service/**
          filters:
            - StripPrefix=1
        #          cart
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart-service/**
          filters:
            - StripPrefix=1
        #          inventory
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/**
          filters:
            - StripPrefix=1
            #          payment
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
          filters:
            - StripPrefix=1
            #          shipping
        - id: shipping-service
          uri: lb://shipping-service
          predicates:
            - Path=/shipping-service/**
          filters:
            - StripPrefix=1
            #          role
        - id: role-service
          uri: lb://shipping-service
          predicates:
            - Path=/shipping-service/**
          filters:
            - StripPrefix=1
            #          permission
        - id: permission-service
          uri: lb://shipping-service
          predicates:
            - Path=/shipping-service/**
          filters:
            - StripPrefix=1



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
